### ISSUE TITLE
Diferentes temáticas preguntas

### ISSUE THREAD

**Issue by MarcosBarrilVillaverde** [Arquisoft/wiq_es6c#116]
El objetivo es realizar la tarea opcional que permite que el sistema puede incluir diferentes temáticas sobre las preguntas y los usuarios podrán elegir entre alguna de las temáticas que van a responder.

**Comment by AbelMH1** [comment]
Suficientemente extendido ya, quedan de todas formas queries planteadas que se podrían añadir a la aplicación cuando resolvamos el resto de asuntos más urgentes
