### ISSUE TITLE
Añadir validaciones al registro de usuarios

### ISSUE THREAD

**Issue by marco-qg** [Arquisoft/wiq_es6c#133]
Evitar usuarios duplicados y campos vacíos o inseguros

**Comment by uo288574** [comment]
En el caso de que se intente registrar un usuario con un nombre que ya consta en el sistema, se mostrará un mensaje al usuario indicándolo. 
Si intentamos añadir un usuario sin rellenar los campos, se mostrará un mensaje notificando que todos los campos deben de rellenarse. 
Y se comprobará la igualdad y longitud de las contraseñas, no permitiendo que estas sean diferentes ni tengan menos de 8 caracteres.
