### ISSUE TITLE
Primera versión de la interfaz del juego con React.js

### ISSUE THREAD

**Issue by alegarman2002** [Arquisoft/wiq_es6c#39]
Creando la primera versión de la interfaz del juego donde vamos a mostrar las preguntas y las diferentes respuestas posibles

**Comment by uo288574** [comment]
Tareas realizadas: 
- Mostrar preguntas y respuestas hardcodeadas. 
- Comprobación de la respuesta pulsada por el jugador.
- Entre una pregunta y otra: 
- --- Si el jugador seleccionó la respuesta correcta -> botón en verde. 
- --- Si el jugador seleccionó la respuesta incorrecta -> botón en rojo y se muestra en verde la respuesta correcta. 
- Incorporación de un círculo de progreso que represente el tiempo que le queda al usuario para contestar a la pregunta.

**Comment by uo288574** [comment]
Tareas realizadas: 
- Hacer llamada a la api que genera las preguntas 
- Procesar las preguntas devueltas por la api. Para cada elemento devuelto:
- --- Almacenamos la pregunta. 
- --- Guardamos la respuesta correcta. 
- --- Juntamos la respuesta correcta con las respuestas incorrectas. 
- --- Ordenamos aleatoriamente el array resultante de juntar todas las posibles respuestas. 

Falta: 
- Mostrar correctamente las preguntas.

**Comment by uo288574** [comment]
Creación de un menú intermedio que separe la vista del login de lo que representa la partida. En esta nueva vista, actualmente sólo tenemos la opción de iniciar una partida. La incorporación de nuevas funciones serán consideraciones futuras. 
En este momento, tras iniciar sesión, se mostrará la opción que nos permitirá crear una partida que estará compuestas por preguntas y respuestas devueltas por la api que contendrá los datos obtenidos de wikidata.
