### ISSUE TITLE
Restricciones de arquitectura

### ISSUE THREAD

**Issue by marco-qg** [Arquisoft/wiq_es6c#6]
Empezar con la redacción del apartado sobre las restricciones de la arquitectura.

**Comment by MarcosBarrilVillaverde** [comment]
**Sobre las restricciones de Arquitectura**

Las restricciones técnicas establecen que la aplicación operará en un entorno Docker y se utilizará GitHub como repositorio remoto para el desarrollo y control de versiones. En términos organizativos, el equipo consta de seis personas y se programan reuniones semanales para discutir la organización de tareas, utilizando herramientas como WhatsApp o Discord si es necesario. Se realizarán pruebas exhaustivas a pesar de la experiencia limitada del equipo con las tecnologías empleadas. En cuanto a las convenciones, la documentación seguirá el método Arc42, la aplicación será accesible para todos los usuarios y se seguirán las convenciones de lenguaje de programación. El código se enfocará en la legibilidad y mantenibilidad, y la aplicación se dividirá en microservicios para facilitar su desarrollo.
