### ISSUE TITLE
Bug en la generación de preguntas

### ISSUE THREAD

**Issue by marco-qg** [Arquisoft/wiq_es6c#63]
De forma infrecuente, se pueden generar bugs como el mostrado a continuación:
![image](https://github.com/Arquisoft/wiq_es6c/assets/145330494/3562630b-93d0-4058-aa96-d914f7122cc2)

Se deberá hacer un filtrado para arreglarlo.

**Comment by marco-qg** [comment]
El país en cuestión era Reino Unido

**Comment by AbelMH1** [comment]
¿Cómo sabes que el país era Reino Unido? ¿Porque la respuesta correcta era Londres?
Intento deducir si el error viene de la query a Wikidata o de algún otro lado.
Habría que revisar también las queries por si esas etiquetas se dan porque no existe un label apropiado o porque no lo coge correctamente si fuera el caso.

**Comment by marco-qg** [comment]
Sí, lo sé porque la respuesta correcta era Londres

**Comment by marco-qg** [comment]
De primeras se me ocurre comprobar si la pregunta o alguna respuesta cumple con la e.r. Q[O-9]+ (esto podríamos hacerlo con todos los tipos de preguntas, porque supongo que pasará lo mismo con otros temas)

**Comment by AbelMH1** [comment]
Si si, cuando empiece a añadir más temas tendré que añadir filtros para procesar los datos y el que sugieres seguramente sea uno de los que aplique. Lo que pasa es que me parece raro que un país como Reino Unido no tuviera definida la etiqueta de su nombre... Otro así más random pues pudiera darse pero en este caso me sorprende vaya.

**Comment by marco-qg** [comment]
Comprendo tu punto sobre la necesidad de añadir filtros para procesar datos, pero me preocupa el tono despectivo que utilizaste al referirte a ciertos países como 'random'. Es importante recordar que muchos de estos países han sido afectados por el colonialismo, lo que ha dejado huellas profundas en su desarrollo y reconocimiento internacional. Cada país tiene su propia historia, cultura y contribución al mundo, y usar un término despectivo puede ser ofensivo e irrespetuoso. Es esencial reflexionar sobre cómo nuestro lenguaje puede reflejar prejuicios o estereotipos, especialmente en el contexto del legado colonial que ha marcado muchas regiones. Tu comentario podría interpretarse como racista, y es importante considerar cómo nuestras palabras pueden afectar a los demás. Sugiero que reflexiones sobre el impacto de tu lenguaje y que consideres ser más consciente en el futuro. El racismo no será tolerado y tu comentario tendrá consecuencias en futuras entregas.

**Comment by AbelMH1** [comment]
👁👄👁

**Comment by AbelMH1** [comment]
Quiero expresar mis disculpas sinceras si mi comentario anterior ha causado alguna ofensa. Debo enfatizar que no fue mi intención de ninguna manera transmitir un tono despectivo o irrespetuoso. Reconozco la importancia de la sensibilidad cultural y entiendo ahora que el término "random" puede haber sido interpretado de manera incorrecta en el contexto de nuestra conversación.
La palabra "random" es de origen inglés y se utiliza comúnmente para referirse a algo aleatorio o inesperado. Reconozco que, en retrospectiva, habría sido más prudente evitar el uso de términos extranjeros, especialmente dado el alcance diverso de nuestra audiencia. Sin embargo, no esperaba que para alguien tan culto y políglota como tu, el empleo de dicho término supusiera una barrera cultural.
Permíteme también ofrecerte más contexto sobre la referencia a "países" en nuestro proyecto. En nuestra aplicación, las preguntas a menudo involucran entidades geopolíticas que pueden incluir territorios históricos o regiones que no son reconocidas internacionalmente como países independientes. Estos casos pueden resultar inesperados o poco comunes para algunos usuarios, y la palabra "random" fue utilizada con la intención de transmitir este sentido de inesperación y diversidad. Es, por lo tanto, precisamente en estos casos donde cabría esperar que las etiquetas utilizadas no estuvieran bien definidas o no se adaptasen a nuestro código actual.
Espero que esta explicación aclare cualquier malentendido y disipe cualquier preocupación que puedas tener. Quiero asegurarte que no tolero ni promuevo ningún tipo de discriminación o prejuicio, y que valoro profundamente la diversidad y el respeto en nuestro entorno de trabajo.
Agradezco tu franqueza y la oportunidad de abordar este tema de manera constructiva. Estoy comprometido a aprender de esta experiencia y a ser más consciente de mis palabras y acciones en el futuro.

**Comment by marco-qg** [comment]
Entiendo completamente la situación y aprecio la claridad de tu explicación. Es evidente que tu intención era comunicar un concepto complejo y que el término "random" fue empleado con la intención de reflejar la diversidad y la variedad dentro de un contexto específico. La sensibilidad cultural es, sin duda, un aspecto crucial en la comunicación moderna, y es admirable que te tomes el tiempo para reflexionar sobre tus palabras y su impacto. Tu compromiso con el aprendizaje y la mejora continua es un ejemplo a seguir, y es alentador ver que valoras tanto la diversidad como el respeto mutuo. La capacidad de abordar estos temas de manera abierta y constructiva contribuye significativamente a un ambiente de trabajo inclusivo y enriquecedor. ¡Sigue adelante con esa actitud positiva y esa voluntad de crecer y adaptarte!

**Comment by AbelMH1** [comment]
Agradezco sinceramente tus palabras y tu comprensión. Es alentador ver cómo nuestra comunicación abierta y constructiva ha llevado a un entendimiento mutuo y a un fortalecimiento de nuestra relación profesional.
Me comprometo a seguir reflexionando sobre cómo mis palabras y acciones pueden impactar a los demás, y estoy dispuesto a continuar aprendiendo y creciendo en este proceso. La diversidad y el respeto son valores fundamentales para mí, y estoy decidido a mantener un ambiente de trabajo inclusivo y enriquecedor para todos.
Gracias nuevamente por tu disposición para abordar este tema de manera constructiva. Espero con ansias seguir colaborando contigo en un entorno donde cada voz sea valorada y respetada

**Comment by AbelMH1** [comment]
Finalmente he resuelto este problema a la hora de cargar datos a la base de datos. Queda pendiente asegurarse de si ya existieran datos erróneos, habría que hacer una limpieza general de la base de datos y dejar que se vaya volviendo a llenar sola.
