### ISSUE TITLE
Estrategia de solución

### ISSUE THREAD

**Issue by marco-qg** [Arquisoft/wiq_es6c#8]
Empezar con la redacción del apartado de la documentación sobre la estrategia de la solución.

**Comment by MarcosBarrilVillaverde** [comment]
Sobre la estrategia de la solución del proyecto, deberemos enfocarnos en las decisiones tecnológicas y organizacionales clave. Vamos a seleccionar tecnologías como ReactJS, TypeScript y MongoDB para garantizar eficiencia y escalabilidad. Además, se ha establecido el inglés como idioma principal y se utilizarán herramientas como GitHub Projects para una gestión eficiente del proyecto.
