### ISSUE TITLE
Arreglar bug inicio sesión

### ISSUE THREAD

**Issue by marco-qg** [Arquisoft/wiq_es6c#85]
Solo afecta al estilo, funciona perfectamente
![image](https://github.com/Arquisoft/wiq_es6c/assets/145330494/bc7925c6-31a7-4466-ac2e-84c5ce0101ec)

**Comment by marco-qg** [comment]
![image](https://github.com/Arquisoft/wiq_es6c/assets/145330494/34af5bad-e034-42d1-b449-29cf59df6c3f)
Otro bug del mismo estilo

**Comment by AbelMH1** [comment]
De locos que se arregló solo, no pasó ni por _In Progress_ xd

**Comment by marco-qg** [comment]
Corrijo con complejidad O(1)
